Create Meme.ts
PrajjwalDatir/Kaoi pull request #241
Opened 2021-11-26 06:59 UTC by Liton124

2021-11-28 10:06 UTC, Oreki-san requested changes
Nice but resources are least it gives same meme after 3-4 commands ,try with different api maybe

2021-11-28 15:22 UTC, Liton124 commented
@Oreki-san  Ok. I'll try

2021-11-29 02:45 UTC, Nisarga-Developer approved these changes

2021-11-30 08:57 UTC, PrajjwalDatir commented
PRs containing APIs hosted on Heroku won't be merged anymore.

2021-11-30 08:57 UTC, closed without merging